### ISSUE TITLE
Unclear whether this will create access to the browser-mounted fs from within a notebook

### ISSUE THREAD

**Issue by VolkerH** [jtpio/jupyterlab-filesystem-access#13]
So I managed to get this to work (thanks for your help in the other issue) and I can run a notebook from a local filesystem mounted through this extension and edit files from my local folder in the Jupyterlab IDE.
What is not quite clear to me (and what got me excited to try this out straight away): will I be able to access this filesystem from within a notebook, e.g. to access some locally saved data from a notebook executed on a remote server?

**Comment by martinRenou** [comment]
> will I be able to access this filesystem from within a notebook

Unfortunately no, at least not if you don't upload manually the file to the remote server first

**Comment by VolkerH** [comment]
Ok thanks for the clarification.

**Comment by jtpio** [comment]
For reference in the case of JupyterLite we might get there eventually, but will require some work upstream (see https://github.com/jupyterlite/jupyterlite/issues/315 for more info).
