### ISSUE TITLE
Problem with build instructions

### ISSUE THREAD

**Issue by VolkerH** [jtpio/jupyterlab-filesystem-access#2]
I am trying to follow the build instructions. (The pip install doesn't work as the package isn't on pypi  (yet?)).

I clone the repo and `cd` into the folder `jupyterlab-filesystem`, i.e. the top-level folder of the cloned repo  (the instructions say to `cd` into `jupyterlab_filesystem` with underscore which I also tried).

`pip instatll -e .` works fine but `jupyter labextension develop . --overwrite` fails.

```
~/Github/jupyterlab-filesystem$ jupyter labextension develop . --overwrite
WARNING: Build tool `jupyter-packaging` is missing. Install it with pip or conda.
An error occurred.
ModuleNotFoundError: There is no labextension at .. Errors encountered: [TypeError("the 'package' argument is required to perform a relative import for '.'"), 
```

**Comment by VolkerH** [comment]
I had already done that but get sill get the error message below the warning. (I copied and pasted the error message before installing `jupyter-packaging`, but it didn't fix it)

**Comment by martinRenou** [comment]
Are you sure you are in the right directory? What would `ls` give you? 

Also please note that this extension is still under development and not really working yet.

**Comment by jtpio** [comment]
Thanks @VolkerH for trying it out.

Normally the build should work from the top-level folder, which is the case on CI: https://github.com/jtpio/jupyterlab-filesystem/runs/5884538225?check_suite_focus=true

As Martin mentioned above, it is still very much under development. We'll publish a first version to PyPI once it's functional.

Of course if you would like to help with PRs that would be very welcome, thanks!

**Comment by VolkerH** [comment]
Thanks for your replies. I had tried both folders. 

I just tried once more, creating a fresh python environment and freshly cloned repo. This time the install went smoothly.
The previous environment was using python 3.8, this fresh one python 3.9, not sure whether this could explain the issues I had (maybe it was just other pre-existing packages int the environment). 

Now I can launch Jupyterlab and see the extension is listed as installed:

![image](https://user-images.githubusercontent.com/2210044/162684592-bf1953ee-e6db-48a5-a8ba-437152392315.png)

However, I don't see the little symbol in the toolbar on the left that is shown in your demo video. If I understand correctly that's what I need to use to mount a local filesystem.

**Comment by VolkerH** [comment]
> As Martin mentioned above, it is still very much under development. We'll publish a first version to PyPI once it's functional.

If I'm just trying this out too early I'm happy to wait a bit longer, but I am quite excited about this as it would hopefully also work with jupyter remote desktop proxies launched from jupyterlab (see https://github.com/VolkerH/Jupyter-Napari-Desktop ) and allow users to upload some of their loccal files to the remote desktop environment via the jupyter lab launcher.

**Comment by jtpio** [comment]
> If I understand correctly that's what I need to use to mount a local filesystem.

@VolkerH are you using a Chromium-based browser? That's one of the biggest limitations for now since the API is not standard:

https://github.com/jtpio/jupyterlab-filesystem-access#jupyterlab-filesystem-access

**Comment by VolkerH** [comment]
Well, it is written all over the readme to use Chromium, but somehow I used mozilla. 
Apologies,  it seems to work now.
Thanks for your help, I will close the issue.

**Comment by jtpio** [comment]
No problem. A `0.2.0` release is under way if you want to try it out.

Thanks for reporting!
